### ISSUE TITLE
[Question] What version of Python does this run on?

### ISSUE THREAD

**Issue by Zeit42** [ba-san/MobilePose-Pi#3]
I'm a bit confused on what version of Python this runs on. 

The guide on how to install PyTorch compiles it using Python 3.6. However, the OpenCV Guide is only for Python 2.7 and Python 3.5. Then when you run the final pip command to install the requirements, by default, it would be for Python 2.7. And finally, when you run the execution for either mobilenet or reset, it's run using just plain python, which would be 2.7.

**Comment by ba-san** [comment]
Hi, thank you for your question.

Actually, Python version of everything you need to install is 2.7.
So, you need to install PyTorch for Python 2.7.
You can do it by searching the method online (Actually, you need to modify some codes if you follow the PyTorch installation guide I shared.), but I would like to write this procedure later, too.

**Comment by ba-san** [comment]
Now you can follow this.
[https://github.com/ba-san/MobilePose-Pi/blob/master/PyTorch_Installation_Guide.md](https://github.com/ba-san/MobilePose-Pi/blob/master/PyTorch_Installation_Guide.md)

**Comment by Zeit42** [comment]
I think that would be best. 

But for the meantime, in this guide [https://wormtooth.com/20180617-pytorch-on-raspberrypi/](on how to install PyTorch), these following commands:

`pip3 install --user pyyaml numpy`

Should be:

`pip install --user pyyaml numpy`

So that pyyaml and numpy would be installed into Python 2.7? 

After that, did you build the PyTorch Library on your own? The link above provided a pytorch wheel available for download, but I think it's for Python 3.6.5.

**Comment by Zeit42** [comment]
Thank you for the clarification. One last question, in the OpenCV Installation Tutorial, it was strongly recommended that we use a virtualenvironment, did you also run that?

**Comment by ba-san** [comment]
To be honest, I didn't make virtualenv this time and I could run the estimation even without it.
But, you know, it is a good practice to prepare virtualenv to avoid conflictions.
So, I also recommend to do it.

Anyway, if you have any further question, please let me know! :)
